### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by hoang-minhhieu** [cache117/peoplesoft-psunit#2]
Hello is me again,

I have some more questions and hope you guys can help. Do you know if there are any way to:
- Show code coverage for PSUnit?
- Make sure that code has been tested by developers using PSUnit (Proof, logs...)

Thanks in advance! 😄

**Comment by jsmpros** [comment]
I do not.

**Comment by cache117** [comment]
There's nothing built it, but it wouldn't be too much of a stretch for you to address your second point. You could add rows to some record of your creation every time a test is run, with the result of the test(s), or something like that.

I'm not aware of anything to be done to show code coverage though. That may be beyond PeopleSoft.
